---
driver:
  name: terraform
  root_module_directory: terratest
  command_timeout: 2400
  color: true    
  
provisioner:
  name: terraform

platforms:
  - name: terraform 

verifier:
  name: terraform
  systems:
    - name: azure
      backend: azure
      controls:
        - azurerm_storage_account

suites:
  - name: default
